services:
  postgres:
    image: postgres:16-alpine
    container_name: agenda-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agenda
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agenda-network

volumes:
  postgres_data:

networks:
  agenda-network:
    driver: bridge
